// Mocks generated by Mockito 5.4.6 from annotations
// in global66_poke_app/test/features/pokedex/presentation/provider/pokedex_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:global66_poke_app/features/pokedex/domain/entities/pokedex_entity.dart'
    as _i6;
import 'package:global66_poke_app/features/pokedex/domain/pagination/pagination_policy.dart'
    as _i3;
import 'package:global66_poke_app/features/pokedex/domain/repositories/pokedex_repository.dart'
    as _i2;
import 'package:global66_poke_app/features/pokedex/domain/usecases/get_pokedex_list_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokedexRepository_0 extends _i1.SmartFake
    implements _i2.PokedexRepository {
  _FakePokedexRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginationPolicy_1 extends _i1.SmartFake
    implements _i3.PaginationPolicy {
  _FakePaginationPolicy_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetPokedexListUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokedexListUsecase extends _i1.Mock
    implements _i4.GetPokedexListUsecase {
  MockGetPokedexListUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokedexRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePokedexRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PokedexRepository);

  @override
  _i3.PaginationPolicy get paginationPolicy =>
      (super.noSuchMethod(
            Invocation.getter(#paginationPolicy),
            returnValue: _FakePaginationPolicy_1(
              this,
              Invocation.getter(#paginationPolicy),
            ),
          )
          as _i3.PaginationPolicy);

  @override
  _i5.Future<List<_i6.PokedexEntity>> call({int? limit, int? offset = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#limit: limit, #offset: offset}),
            returnValue: _i5.Future<List<_i6.PokedexEntity>>.value(
              <_i6.PokedexEntity>[],
            ),
          )
          as _i5.Future<List<_i6.PokedexEntity>>);
}
