// Mocks generated by Mockito 5.4.6 from annotations
// in global66_poke_app/test/features/favorites/data/repositories/favorites_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:global66_poke_app/features/favorites/data/datasource/favorites_local_datasource.dart'
    as _i3;
import 'package:global66_poke_app/features/favorites/data/models/favorite_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FavoritesLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesLocalDatasource extends _i1.Mock
    implements _i3.FavoritesLocalDatasource {
  MockFavoritesLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<void> addFavorite(_i5.FavoriteModel? favorite) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [favorite]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFavorite(int? pokemonId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavorite, [pokemonId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.FavoriteModel>> getAllFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getAllFavorites, []),
            returnValue: _i4.Future<List<_i5.FavoriteModel>>.value(
              <_i5.FavoriteModel>[],
            ),
          )
          as _i4.Future<List<_i5.FavoriteModel>>);

  @override
  _i4.Future<bool> isFavorite(int? pokemonId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [pokemonId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> clearAllFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllFavorites, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
